services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend-build
    ports:
      - '5173:4173'
    environment:
      - NODE_ENV=production
    command:
      [
        'sh',
        '-c',
        "cd /app/frontend && echo 'Starting frontend...' && bun run start"
      ]

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend-build
    environment:
      - NODE_ENV=production
    command:
      [
        'sh',
        '-c',
        "cd /app/backend && echo 'Starting backend...' && bun run start"
      ]
    deploy:
      replicas: 3

  nginx:
    image: nginx:alpine
    ports:
      - '3000:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
