services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend-build
    ports:
      - '4173:4173'
    environment:
      - NODE_ENV=production
    command:
      [
        'sh',
        '-c',
        "cd /app/frontend && echo 'Starting frontend...' && npm run start"
      ]

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend-build
    #    ports:
    #      - '3000:3000'
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
    command:
      [
        'sh',
        '-c',
        "cd /app/backend && echo 'Starting backend...' && bun run start"
      ]
    depends_on:
      - redis
    deploy:
      replicas: 3

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
